# Generated by Django 3.2.7 on 2021-09-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_liked_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liked_posts',
            field=models.TextField(default='{1:False}'),
        ),
    ]
