# Generated by Django 3.2.7 on 2021-09-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_liked_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.CharField(blank=True, default=0, max_length=999999999, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.CharField(blank=True, default=0, max_length=999999999, null=True),
        ),
    ]
