# Generated by Django 3.2.7 on 2021-10-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_liked_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notifications',
            field=models.TextField(default=''),
        ),
    ]
