# Generated by Django 3.2.7 on 2021-10-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.TextField(default=''),
        ),
    ]
