# Generated by Django 3.2.7 on 2021-09-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_users_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
