# Generated by Django 3.2.7 on 2021-09-17 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_post_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='image',
        ),
    ]
