# Generated by Django 3.2.7 on 2021-09-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_post_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.CharField(default=0, max_length=999999999999999999999999),
            preserve_default=False,
        ),
    ]
