# Generated by Django 3.2.7 on 2021-09-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.CharField(default='', max_length=999999999999999999999999),
        ),
    ]
