# Generated by Django 3.2.7 on 2021-09-30 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_post_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='post_comment',
        ),
    ]
